### ISSUE TITLE
How get all properties in object? 

### ISSUE THREAD

**Issue by krogal1985** [Frozenlock/wacnet#12] opened 2018-09-10 12:38 UTC
if get URL API:
http://localhost:47800/api/v1/bacnet/devices/2098204/objects/1.12?properties=present-value
get normal value:
![image001](https://user-images.githubusercontent.com/29096495/45297792-e8413000-b51f-11e8-9771-0b9e9f5c341a.png)
I wont get all properties i get URL API:
http://localhost:47800/api/v1/bacnet/devices/2098204/objects/1.12
but response error:
```
500: Internal Server Error

There was an internal server error.

clojure.lang.ExceptionInfo: Error on GET {:response #yada.context.Response{:headers {}, :vary #{:media-type}, :produces {:media-type #yada.media_type.MediaTypeMap{:name "text/html", :type "text", :subtype "html", :parameters {}, :quality 1.0}, :charset #yada.charset.CharsetMap{:alias "UTF-8", :quality 1.0}}}, :resource yada.resource.Resource, :error #error {

:cause nil

:via

[{:type com.serotonin.bacnet4j.exception.ReflectionException

   :message "java.lang.reflect.InvocationTargetException"

   :at [com.serotonin.bacnet4j.type.Encodable read "Encodable.java" 214]}

  {:type java.lang.reflect.InvocationTargetException

   :message nil

   :at [sun.reflect.GeneratedConstructorAccessor25 newInstance nil -1]}

  {:type java.lang.NullPointerException

   :message nil

   :at [com.serotonin.bacnet4j.type.AmbiguousValue attemptConversion "AmbiguousValue.java" 139]}]

:trace

[[com.serotonin.bacnet4j.type.AmbiguousValue attemptConversion "AmbiguousValue.java" 139]

  [com.serotonin.bacnet4j.type.Encodable readEncodable "Encodable.java" 338]

  [com.serotonin.bacnet4j.type.constructed.ReadAccessResult$Result  "ReadAccessResult.java" 134]

  [sun.reflect.GeneratedConstructorAccessor25 newInstance nil -1]

  [sun.reflect.DelegatingConstructorAccessorImpl newInstance nil -1]

  [java.lang.reflect.Constructor newInstance nil -1]

  [com.serotonin.bacnet4j.type.Encodable read "Encodable.java" 202]

  [com.serotonin.bacnet4j.type.constructed.SequenceOf  "SequenceOf.java" 80]

  [com.serotonin.bacnet4j.type.Encodable readSequenceOf "Encodable.java" 273]

  [com.serotonin.bacnet4j.type.Encodable readOptionalSequenceOf "Encodable.java" 307]

  [com.serotonin.bacnet4j.type.constructed.ReadAccessResult  "ReadAccessResult.java" 72]

  [sun.reflect.GeneratedConstructorAccessor28 newInstance nil -1]

 [sun.reflect.DelegatingConstructorAccessorImpl newInstance nil -1]

  [java.lang.reflect.Constructor newInstance nil -1]

  [com.serotonin.bacnet4j.type.Encodable read "Encodable.java" 202]

  [com.serotonin.bacnet4j.type.constructed.SequenceOf  "SequenceOf.java" 68]

  [com.serotonin.bacnet4j.type.Encodable readSequenceOf "Encodable.java" 262]

  [com.serotonin.bacnet4j.service.acknowledgement.ReadPropertyMultipleAck  "ReadPropertyMultipleAck.java" 58]

  [com.serotonin.bacnet4j.service.acknowledgement.AcknowledgementService createAcknowledgementService "AcknowledgementService.java" 56]

  [com.serotonin.bacnet4j.apdu.ComplexACK parseServiceData "ComplexACK.java" 208]

  [com.serotonin.bacnet4j.transport.DefaultTransport completeComplexAckResponse "DefaultTransport.java" 651]

  [com.serotonin.bacnet4j.transport.DefaultTransport receiveAPDU "DefaultTransport.java" 585]

  [com.serotonin.bacnet4j.transport.DefaultTransport receiveImpl "DefaultTransport.java" 472]

  [com.serotonin.bacnet4j.transport.DefaultTransport run "DefaultTransport.java" 412]

  [java.lang.Thread run nil -1]]}}

        at clojure.core$ex_info.invokeStatic(core.clj:4617)

        at clojure.core$ex_info.invoke(core.clj:4617)

        at yada.methods$fn__20207$fn__20218.invoke(methods.clj:198)

        at manifold.deferred$catch_SINGLEQUOTE_$fn__5395.invoke(deferred.clj:963)

        at manifold.deferred.Listener.onError(deferred.clj:220)

        at manifold.deferred.Deferred$fn__5175$fn__5176.invoke(deferred.clj:399)

        at clojure.lang.AFn.run(AFn.java:22)

        at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)

        at manifold.executor$thread_factory$reify__4680$f__4681.invoke(executor.clj:44)

        at clojure.lang.AFn.run(AFn.java:22)

        at java.lang.Thread.run(Unknown Source)
```

**Comment by Frozenlock** [comment] 2018-09-10 18:17
This looks like a duplicate of https://github.com/Frozenlock/wacnet/issues/8.

Could you make the port 47999 available? (Or a VLAN access?) This way I could try to determine the cause.

**Comment by krogal1985** [comment] 2018-09-11 06:10
port 47999 normal available

**Comment by Frozenlock** [comment] 2018-09-11 06:47
I don't think you understand.
I want to connect on port 47999. This means you need to open the port and give me your IP address.
You can the info at cfortin@hvac.io.

**Comment by krogal1985** [comment] 2018-09-12 11:00
Sorry, but I can not provide access, there is a closed system, can I follow through on your recommendations?

**Comment by Frozenlock** [comment] 2018-09-12 17:23
There is nothing to be done if I can't have access to debug.
I'll close this and let the duplicate issue open.

**Closed as completed by Frozenlock** 2018-09-12 17:23 UTC
